title: Anabel Arasanz
description: Computational Linguist | NLP & AI Specialist

baseurl: ""
url: https://anbat3.github.io

theme: cvless

# site settings
taglong: Computational Linguist | NLP & AI Specialist
tagshort: NLP & AI Specialist

# author settings
author:
  name: Anabel Arasanz
  email: anabelarasanz@disroot.org

photo: assets/files/photo.png

joblines:
  - Computational Linguist
  - NLP & AI Specialist
  - Madrid, Spain

address: Madrid, Spain
phone:

# profile links
profile:
  linkedin: https://www.linkedin.com/in/anabelarasanz
  github: https://github.com/anbat3
  cv: true

# build settings
permalink: pretty

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never